Port to GTK4
elementary/feedback pull request #54
Opened 2022-01-08 00:46 UTC by danrabbit

Todo:
- [ ] Fix saving and restoring window size
- [ ] Fix only showing check for selected row
- [ ] Panel & System Settings are empty. Possible due to deprecated `AppStream.Pool.clear_metadata_locations` and `AppStream.Pool.add_metadata_location`

2022-05-07 19:13 UTC, Marukesu commented
Looks like the flatpak CI ended in an false positive, i also can't build it locally (fails building xapian).

2022-12-20 07:20 UTC, zeebok submitted a review, later dismissed

2022-12-23 10:41 UTC, lenemter requested changes
Category title is always wrapped, while it isn't in Gtk 3 version.

Gtk 4:
![image](https://user-images.githubusercontent.com/80143868/209321603-226499a4-6c6f-4441-ab71-7eee6ba6240b.png)

Gtk 3:
![image](https://user-images.githubusercontent.com/80143868/209321809-3992b0fe-fc25-44b3-8c57-eb2f22f99bad.png)

2023-01-15 04:59 UTC, zeebok submitted a review, later dismissed

2023-01-18 10:06 UTC, lenemter approved these changes

2023-01-18 16:29 UTC, merged